### ISSUE TITLE
cuke_modeler `cucumber_gherkin` dependency breaks cucumber specs / parallel specs

### ISSUE THREAD

**Issue by alexanderjeurissen** [enkessler/cuke_modeler#6]
Thanks for the work, this looks great.

I was actually working on building a decent cucumber parser myself and stumbled upon this project 😄 

I'd love to use this for a project, but am running into some issues where a dependency conflict seems to break the cucumber runner, both when using spring as well as using `parallel_tests`:

error message:

```
|| [TEST PROF INFO] Spring detected
||  set_config 
|| ------------
||  
|| (1 row)
|| 
/Users/alexanderjeurissen/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core/gherkin/ast_builder.rb|81 error| undefined method `keys' for #<Cucumber::Messages::GherkinDocument::Feature:0x00007f8c4cd04f78>
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core/gherkin/ast_builder.rb:32:in `initialize'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core/gherkin/ast_builder.rb:125:in `initialize'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core/gherkin/ast_builder.rb:106:in `new'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core/gherkin/ast_builder.rb:106:in `feature'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core/gherkin/ast_builder.rb:17:in `feature'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core/gherkin/parser.rb:32:in `document'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core.rb:30:in `block in parse'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core.rb:29:in `each'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core.rb:29:in `parse'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-core-3.2.1/lib/cucumber/core.rb:21:in `compile'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/lib/cucumber/runtime.rb:75:in `run!'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/lib/cucumber/cli/main.rb:34:in `execute!'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cucumber-3.2.0/bin/cucumber:9:in `<main>'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
|| Development/project/bin/cucumber:8:in `<main>'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/command_wrapper.rb:40:in `call'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:220:in `block in serve'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:180:in `fork'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:180:in `serve'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
|| .rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
|| .rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
|| .rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
|| -e:1:in `<main>'
```

content of `bin/cucumber`:

```
#!/usr/bin/env ruby
begin
  load File.expand_path('../spring', __FILE__)
rescue LoadError => e
  raise unless e.message.include?('spring')
end
require 'bundler/setup'
load Gem.bin_path('cucumber', 'cucumber')
```

The issue also occurs when invoking cucumber without spring.

relevant content of `Gemfile.lock`:

```
    cucumber (3.2.0)
      builder (>= 2.1.2)
      cucumber-core (~> 3.2.0)
      cucumber-expressions (~> 6.0.1)
      cucumber-wire (~> 0.0.1)
      diff-lcs (~> 1.3)
      gherkin (~> 5.1.0)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.2)
    cucumber-core (3.2.1)
      backports (>= 3.8.0)
      cucumber-tag_expressions (~> 1.1.0)
      gherkin (~> 5.0)
    cucumber-expressions (6.0.1)
    cucumber-gherkin (16.0.0)
      cucumber-messages (~> 13.2, >= 13.2.1)
    cucumber-messages (13.2.1)
      protobuf-cucumber (~> 3.10, >= 3.10.8)
    cucumber-rails (1.8.0)
      capybara (>= 2.12, < 4)
      cucumber (>= 3.0.2, < 4)
      mime-types (>= 2.0, < 4)
      nokogiri (~> 1.8)
      railties (>= 4.2, < 7)
    cucumber-tag_expressions (1.1.1)
    cucumber-wire (0.0.1)
    cuke_linter (1.1.0)
      cuke_modeler (>= 1.5, < 4.0)
    cuke_modeler (3.5.0)
      cucumber-gherkin (< 17.0)

    protobuf-cucumber (3.10.8)
      activesupport (>= 3.2)
      middleware
      thor
      thread_safe

    spring-commands-cucumber (1.0.1)
      spring (>= 0.9.1)

    cucumber-rails (= 1.8.0)
```

Seems I'm not alone in this: https://stackoverflow.com/questions/62952103/undefined-method-keys-for-cucumbermessagesgherkindocumentfeature0x080

**Comment by enkessler** [comment]
You're not alone in this at all! Welcome to the Conflict Club!

It looks like you are using `cucumber` 3.x, which uses `cucumber-core` 3.x, which uses the `gherkin` gem. You are also using `cuke_modeler` 3.x, which uses the `cucumber-gherkin` gem. Your problem is that `gherkin` and `cucumber-gherkin` cannot co-exist as dependencies (see https://github.com/cucumber/cucumber/issues/1063).

**Solution**: either upgrade your `cucumber` gem to 4.x (which transitively uses `cucumber-gherkin`) or downgrade your `cuke_modeler` gem to 2.x (which uses `gherkin`).

**Comment by alexanderjeurissen** [comment]
That makes sense, thanks for coming back to me on such short notice.

Downgrading for now was the quickest way to get `cuke_modeler` in our codebase, I'll revisit upgrading at a later point.

Thanks again

**Comment by enkessler** [comment]
You're welcome! I'm always glad to see someone getting some use out of this gem.
